### ISSUE TITLE
Tree improvements

### ISSUE THREAD

**Issue by glebovsky** [intelliants/subrion#104]
There is a bug in Tree jquery plugin: it is possible to add node to its children or even inside self. We need to lock self node, when editing item.

This issue relates not to Tree field! This relates to adding locations and categories..

**Comment by vbezruchkin** [comment]
I guess we also need a way to order tree nodes. Really, it's important.

**Comment by vbezruchkin** [comment]
This issue is fixed. I imported categories dump in Directory package (utilizes common Category helper) and it does not display inner categories & itself when you edit a category.

So there is no way to move a category inside one of children categories.

Issue regarding ordering trees is also resolved.
