### ISSUE TITLE
Manual https config? Location?

### ISSUE THREAD

**Issue by archae0pteryx** [intelliants/subrion#197]
I'm having a problem with the csrf because of https permanent redirect I think. How might one manually update this config? What I am asking specifically is: Since I cannot apply any settings in the admin because of CSRF, where might the ol' boy (configuration) live (path/to/csrf switch)?

**Comment by 4unkur** [comment]
Hello @archae0pteryx,

Config values are stored in the database. You can find them in `{prefix}config` table, where `{prefix}` is a prefix that you assigned while installation process.  
config for disabling CSRF prevention has `name` of `prefent_csrf` after that you may to empty `tmp` folder and try to login to admin panel.  
Also, if you have your site on HTTPS, then you have to enable HTTPS config in admin panel -> System -> HTTPS.  
Please let us know how it goes for you.

**Comment by vbezruchkin** [comment]
I guess that's more a private use case rather than a specific software issue.

The main truth is to have the system configured properly:
If you use it on https:// - it should have https:// in **baseurl** configuration

There could be some redirects in .htaccess to redirect from one protocol to anotherr, and we'd recommend to configure this properly.

If you have any questions we will be happy to assist via helpdesk. Thanks
