### ISSUE TITLE
Review hooks inclusion

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion#385]
Make sure files are included correctly. 

Hooks/blocks/pages should have the same filename inclusion structure. 

Templates can also have external blocks/hooks/pages and they should have an easier way of inclusion.

Fix.

**Comment by vbezruchkin** [comment]
Please discuss. It's major version update that would require plugins update so I guess it's time to workout one standard approach for all files inclusion.

Thanks

**Comment by Batry** [comment]
Done in https://github.com/intelliants/subrion/commit/4bb8ee916986116db3022836aac2417906e44ab1, https://github.com/intelliants/subrion/commit/69567e7355d11f40eb7ee2eaa98f194cde3787d1.

Backward compatibility kept.

---

File extension should be always specified for hooks as well as blocks:

```
<hook name="myHookName"... filename="hook.blocks-load.php"></hook>
<block name="myBlock"... type="smarty" filename="block.cart.tpl"></block>
```

In order to include TPL file the following scheme should be used:

`module:modulename/templatename.tpl`

instead of `extra:modulename/templatename`.

**Comment by vbezruchkin** [comment]
Thanks. It looks ok now.
