### ISSUE TITLE
Incorrect working of multilingual config on Add / Edit field page

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#426]
For example, I have some data in `description` field and it's not multilingual.
If I go to **Subrion Admin Panel -> Content -> Fields** -> **edit** this field -> enable the **'Multilingual'** config -> click on **'Save'** button -> all the data in `description` column will be lost as this column will be removed and system will create new columns like `description_en`, `description_ru` and etc.

Issue exists during disabling this config too.

**Comment by vbezruchkin** [comment]
@Batry The issue is invalid. I was unable to reproduce this problem using member field Biography.

The field is never deleted, and correct language related columns are added. I believe @agorshechnikov had just a temp issue with that when the feature was not 100% complete.

Anyhow, there is still a small issue - the value is not being save into new language columns when multilingual field is activated. We need to discuss this and decide if we really expect this behavior.

Thanks

**Comment by Batry** [comment]
As per discussion, the main language's content will be transferred to all other languages automatically.

It's done.
