### ISSUE TITLE
Problem with CloudFlare SSL

### ISSUE THREAD

**Issue by ddnas** [intelliants/subrion#485]
Hi, i use the last version of Subrion and i have a issue on Cloudflare SSL. I enable the HTTPS option on subrion panel and i check tha the database have the https://..... I enable https on cloudflare for my site and after that i visit my site and i can see my home page with "Error 404" and all module pages are with the same error. Other pages and pages wich i create works without problem. (Tested with Flexible SSL and with Full SSL). Any idea to sovle it ?

Thank you

**Comment by 4unkur** [comment]
Hello @ddnas,

Probably this happens because of the browsers cache. When you type domain.com it tries to open HTTP://domain.com instead of HTTPS://domain.com  

To change such behavior you may activate redirect from HTTP to HTTPS in `.htaccess` file:  
```
    # RewriteCond %{HTTPS} off
    # RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```

Just remove the `#` symbol from the beginning of these lines.

Thanks.

**Comment by ddnas** [comment]
I do it but nothing. Additionally after this i delete all files of tmp folder. Any other idea ?

Thanks

**Comment by 4unkur** [comment]
Could you please submit at ticket in our [Help Desk](https://www.subrion.com/desk/) with URL of your website and FTP access. We'll investigate it and fix.

Thanks.

**Comment by ddnas** [comment]
Yes of course. Thank you for your quickly reply.

**Comment by 4unkur** [comment]
Issue has been fixed via HelpDesk.  

About the solution:  
We have some issues with CloudFlare SSL certificates.

in https://github.com/intelliants/subrion/blob/develop/includes/classes/ia.core.php#L201
it defines, whether domain is under HTTPS or not.
with CloudFlare certificates `$_SERVER['HTTPS']` variable is not set, that's why check fails and it treats like it's not HTTPS even if it is.
The possible solution is to add another check for connection port (443) if `$_SERVER['HTTPS']` is not set.

**Comment by vbezruchkin** [comment]
We had the same CloudFlare SSL cert for one of our customers. No issues. Also there is a notification during the installation so we can consider this issue resolved. 

We will reopen it again if there is any issue.

Thanks
