### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Beltasbur** [intelliants/subrion#499]
Hello there,

I cannot access my administrator panel after fresh install, I have all of the requirements, and these are the versions I'm using:

Apache: 2.4.27
PHP: 7.1.8
MySQL: 5.7.19
Subrion: 4.1.5

I can provide SSH/FTP access if needed, thanks.

**Comment by vbezruchkin** [comment]
Hello,

Apologizes for the delay with reply. This is definitely related to an update to 4.1.5.10 that does not work correctly on specific servers. 

Yes, please [submit your ftp details](https://www.subrion.com/desk/index.php?/Tickets/Submit) so we could check this directly on your server.

Thanks

**Comment by Beltasbur** [comment]
Ticket sent through Technical Support department, let me know if anything else is needed. Also please explain how am I supposed to fix it when it's complete. Thanks!

**Comment by vbezruchkin** [comment]
Thanks. We've started to work on the case. We will get in touch via ticket system once we manage to solve it.

**Comment by gesonchi** [comment]
@vbezruchkin If SBRCMS develops "ticket system", it is very important for internal communication, and front end user feedback, and I hope you consider it.

**Comment by vbezruchkin** [comment]
I guess the issue was fixed through the helpdesk system.

@gesonchi thanks for your request. Unfortunately a ticket system would be a complicated module to work on, and we have similar request here: https://github.com/intelliants/subrion/issues/503 so we will use it for progress and post our idea regarding your request there.

Thanks
