### ISSUE TITLE
safety problem

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#509]
1

Why in the root directory to join phpmyadmin, will jump to 404 pages? For security reasons, or database tools to consider?

2

/ panel can be modified as a secondary domain name?

**Comment by vbezruchkin** [comment]
Hi,

1. It's related to the .htaccess redirection rules for CMS. You need to put .htaccess in phpmyadmin folder with the following content:
```
RewriteEngine Off
```
And it will be available. Otherwise everything is redirected to subrion cms index.php controller.

2. No, you cannot configure admin folder as a subdomain. But you can easily change it to anything else in admin dashboard. Please check subrion system settings.

Cheers

**Comment by JialuZhang** [comment]
@vbezruchkin 

In your posted configuration,
```
RewriteEngine Off
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
