### ISSUE TITLE
How to use smarty template to achieve the following results.

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#525]
How to use smarty template to achieve the following results.

For example, the time function is expressed as:

Just 1 hour ago, more than 1 hour, showing the specific time format, shown as: 2017-9-13 01:29

https://www.smarty.net/docsv2/en/language.modifier.date.format
——————————————

public class FormatCurrentData {
      
    / ** Set each stage time * /
    private static final int seconds_of_1minute = 60;
  
    private static final int seconds_of_30minutes = 30 * 60;
  
    private static final int seconds_of_1hour = 60 * 60;
  
    private static final int seconds_of_1day = 24 * 60 * 60;
  
    private static final int seconds_of_15days = seconds_of_1day * 15;
  
    private static final int seconds_of_30days = seconds_of_1day * 30;
  
    private static final int seconds_of_6months = seconds_of_30days * 6;
  
    private static final int seconds_of_1year = seconds_of_30days * 12;
  
    / **
     * Format time
     * @param mTime
     * @return
     * /
    public static String getTimeRange (String mTime)
    {
        SimpleDateFormat sdf = new SimpleDateFormat ("yyyy-MM-dd HH: mm: ss");
        / ** Get current time * /
        Date curDate = new Date (System.currentTimeMillis ());
        String dataStrNew = sdf.format (curDate);
        Date startTime = null;
        try {
            / ** Converts time to Date * /
            curDate = sdf.parse (dataStrNew);
            startTime = sdf.parse (mTime);
        } catch (ParseException e) {
            e.printStackTrace ();
        }
        / ** divided by 1000 is to convert to seconds * /
        long between = (curDate.getTime () - startTime.getTime ()) / 1000;
        int elapsedTime = (int) (between);
        if (elapsedTime <seconds_of_1minute) {
  
            "just";
        }
        if (elapsedTime <seconds_of_30minutes) {
  
            return elapsedTime / seconds_of_1minute + "minutes ago";
        }
        if (elapsedTime <seconds_of_1hour) {
  
            return "half an hour ago";
        }
        if (elapsedTime <seconds_of_1day) {
  
            return elapsedTime / seconds_of_1hour + "hours ago";
        }
        if (elapsedTime <seconds_of_15days) {
  
            return elapsedTime / seconds_of_1day + "days ago";
        }
        if (elapsedTime <seconds_of_30days) {
  
            "half a month ago";
        }
        if (elapsedTime <seconds_of_6months) {
  
            return elapsedTime / seconds_of_30days + "month ago";
        }
        if (elapsedTime <seconds_of_1year) {
  
            "six months ago";
        }
        if (elapsedTime> = seconds_of_1year) {
  
            return elapsedTime / seconds_of_1year + "years ago";
        }
        return "";
    }

**Comment by vbezruchkin** [comment]
Hi,

Please note we use Smarty 3 which offers a lot of improvements. In order to improve this you'd need to create smarty modifier that would format the date according to the styled format. 

I believe it's more a Smarty related question, and I'm sure you can discuss it here:
https://github.com/smarty-php/smarty/issues

I suppose they might have done something similar for someone and I believe they might have some ideas how to achieve this.

Another option would be to use some sort of JS plugin that would do the same for you. So you can hack default smarty modifier (includes/smarty/plugins/modifier.date_format.php) and make it output the formatted time in wrapped format like: <span class="js-date-format">date</span> and use https://momentjs.com/ library for example and link it to js-date-format span.

No other ways is possible now, because there is no multi-lingual library and our system is used for many languages.

Cheers
