### ISSUE TITLE
Discuss the difficulty of secondary development of SBRCMS

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion#561]
Why is it difficult to use SBRCMS secondary development?

The theme template file does not seem to be in the same directory, such as the "magazine" folder.

Why not follow the "htm" file architecture to design templates.
Such as the attachment sample image design.

![qq 20171007191652](https://user-images.githubusercontent.com/7976867/31307302-3fde2c32-ab94-11e7-8b69-572d7c59c00a.jpg)

**Comment by vbezruchkin** [comment]
Hi,

Not sure if I understand the question. Really.
Do you want to use htm files instead of tpl files? Tpl files are smarty filetype and they can be easily edited in any html editor. If you need a custom design for specific pages just copy the default template from the original location and put into the template folder - it will be used then.

Let's say you can a custom edit profile page - it uses profile.tpl file. If you want to have a custom one in  your specific template copy that template from templates/_common/ to your templates/YOUR_TEMPLATE - that's it.

This can be also done for plugins and packages as well. In 4.1.x just copy necessary template to templates/YOUR_TEMPLATE/modules/MODULE_NAME/template_name.tpl and it will be used by the system.

Cheers

**Comment by gesonchi** [comment]
hi , vbezruchkin!

I'm glad to see you again。

I also have a very important question about using the SBR template.
Has been puzzling me for a long time.
Use custom templates to add time on the background page.
However, custom templates are displayed in the content area of the page.
I want custom templates without header and footer and no sidebar.
Just need to display the contents of the custom template, that's all.
I don't know if you can fully understand what I'm doing because of the Chinese translation.
Next, I draw a picture of this new problem to help you understand my problem.

![-1 fw](https://user-images.githubusercontent.com/7976867/31309414-5f25adc6-abb8-11e7-8c31-4aa8956cb6e6.png)

**Comment by vbezruchkin** [comment]
Hi,

This could be easily done in our system. If you want to create a new page using module, and it has it's own controller you can do the following:

```
$iaView->disableLayout(); // this method prevents default layout.tpl loading
$iaView->display('CUSTOM_TEMPLATE'); // this method defines what file should be used
```
You can add it to your php controller file.

If you want this for your custom page, created in admin page you need to update front/page.php file

just change this code:
```
$iaView->display('page');
```
to the following:
```
if ('YOUR_PAGE_NAME' == $iaView->name()) { 
  $iaView->disableLayout(); // this method prevents default layout.tpl loading
  $iaView->display('CUSTOM_TEMPLATE'); // this method defines what file should be used
} else { 
  $iaView->display('page');
}
```
Please note that CUSTOM_TEMPLATE file should be placed into templates/template_name/ folder and it should include your header/footer section, etc. 

Try the solution and let us know the results please.

Cheers
