### ISSUE TITLE
CSRF Attack On Change Password!

### ISSUE THREAD

**Issue by TusharKdm** [intelliants/subrion#638]
Hi Team,
The application is vulnerable to CSRF attack.
Affected Application Version: Subrion CMS 4.1.5

The attacker can change the administrator password by sending a crafted request to the application on change password field.
The application is not validating the source origin of the request is coming from also CSRF token is not implemented. 

**Proof of concept as given below**
1. Crafted Code of Change Password of Administrator User.

![csrf attacke code](https://user-images.githubusercontent.com/36395331/36137449-4ad05bc4-10bb-11e8-8618-f3530ac7901e.png)

2. Crafted Request to Change the Password of Administrator.

![csrf crafted request](https://user-images.githubusercontent.com/36395331/36137562-d87d58be-10bb-11e8-8487-a437b069cb0c.png)

3. The Password is Changed Successfully. 

![password changed successfully](https://user-images.githubusercontent.com/36395331/36137619-14e3da9e-10bc-11e8-8fce-ead0a1cc9a26.png)

Recommendation:  
1. Implement CSRF Token.
2. Validate the Source Origin 

When you fix the bug, please, can you include my name in the release notes when the bug will be corrected? 
Name : Tushar Kadam
Email : kadatushar@gmail.com 

Thank you.

**Comment by Batry** [comment]
Hi @TusharKdm!

Thanks for your report.

Regarding your recommendations, please kindly be informed that the issue has already been fixed in upcoming 4.2.0 version. Solution meets both of your recommendations: _Implement CSRF Token_ and _Validate the Source Origin_.

Here an important thing should be noted. As per shown in your POC, you changed the password being logged in as Superadministrator user. No any regular user or even user having moderator privileges may not change the data of other users. Definitely, there should be an understanding that attach of such type makes no sense in real life.

**Comment by TusharKdm** [comment]
Ok Great you have already closed the issue.

FYI,
CSRF attack only possible when a user is logged in to the application,
so the attacker can create crafted request and can send this crafted request to the user via mail or any source then unfortunately if the admin user clicked on the request then the attacker can change the password of that admin user.

Thank you.
