### ISSUE TITLE
blog post on stored xss vulnerability

### ISSUE THREAD

**Issue by ismailtasdelen** [intelliants/subrion#753]
Hello Subrion Development Team,

My name is Ismail Tasdelen. I am a security researcher. I found the xss security vulnerability stored on blog posting stored. And I want to report to you.

After I fix the weakness, I want the video to be published. You could provide a security clear CVE number.

Besides, is it possible to pay for a security investigation ?

Software : Subrion CMS 4.2.1 > Last Version

XSS Payload : "><img src=x onerror=alert('ismailtasdelen')>

Video PoC : https://drive.google.com/open?id=1y_FnWtLqFD9BS2u2UYNMlhS8FK8vCoxP

Screenshot :

![screenshot from 2018-07-07 01-41-25](https://user-images.githubusercontent.com/15425071/42404265-54c63a90-8190-11e8-91a4-2414daac8922.png)

I'm waiting for you to come back, please come back on the subject.

Ismail Tasdelen - Global Security Researcher

**Comment by ismailtasdelen** [comment]
Thanks for the came back :+1:

**Comment by 4unkur** [comment]
Hi @ismailtasdelen,

Thank you for you investigation indeed, but this bug is related to the obsolete 4.0.5 version of the script.
Unfortunately we haven't updated our Demo websites yet to the latest version.
This bug has been already fixed in the previous patches and the latest Subrion CMS version (4.2.1) doesn't contain such vulnerability. 

> Besides, is it possible to pay for a security investigation ?

Unfortunately we doesn't have any bounty programs.

Thanks.

**Comment by ismailtasdelen** [comment]
Thanks for the came back :+1:
