### ISSUE TITLE
Broken CSRF check in login panel

### ISSUE THREAD

**Issue by rishaldwivedi** [intelliants/subrion#761]
Version tested on - Subrion CMS v4.2.1

Whenever a user logs into the Admin or user panel. A unique token is generated, added to the login form & the login HTTP request in order to prevent CSRF attack. 

Actual behavior - The protection is broken as it logs in the user even if the token match fails.
Expected behavior - It should restrict the request from being processed further. 

Steps to reproduce - 

- Initiate the below POST request 
**URL** - http://localhost/subrion-develop/panel/
**POST request** - 
__st=someinvalidtoken&username=admin&password=admin
(Make sure the credentials are correct)

- Application would throw a potential CSRF attack error. 
- Just refresh the webpage, user would be logged in.

**Comment by 4unkur** [comment]
Thanks for the report. We've checked this and issue exists indeed.  
We'll fix this in one of our upcoming patches

**Comment by Tarx112** [comment]
I have tried everything and support writing is not helpful. I sent login passwords to improve the script. I'm waiting for over a week. The whole home page can not work. the problem is only when admin is logged in. access denied If you change privileges, all users of the admin panel will be logged in.
